# Generated by Django 5.1.2 on 2024-11-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"verbose_name": "привычка", "verbose_name_plural": "привычки"},
        ),
        migrations.AlterModelOptions(
            name="place",
            options={"verbose_name": "место", "verbose_name_plural": "места"},
        ),
        migrations.AlterModelOptions(
            name="reward",
            options={
                "verbose_name": "вознаграждение",
                "verbose_name_plural": "вознаграждения",
            },
        ),
        migrations.RemoveField(
            model_name="habit",
            name="time_to_complete",
        ),
    ]
