# Generated by Django 5.1.2 on 2024-11-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_options_alter_place_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="time_to_complete",
            field=models.PositiveIntegerField(
                default=0, verbose_name="время на выполнение"
            ),
            preserve_default=False,
        ),
    ]
