# Generated by Django 5.1.2 on 2024-11-09 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_time_to_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="habits",
                to="habits.reward",
                verbose_name="вознаграждение",
            ),
        ),
    ]
